# SPDX-FileCopyrightText: 2021 - 2023 Mewbot Developers <mewbot@quicksilver.london>
#
# SPDX-License-Identifier: CC0-1.0

[tool.bastet]

disable = ["isort", "black"]

[tool.ruff.lint]

select = ["ALL"]
ignore = [
    "D200",  # Single line doc strings do not need to fit on a single line in code.
    "D203",  # Zero blank lines before docstring.
    "D202",  # One blank line after docstring.
    "D212",  # Multi-line docstring summary should start at the second line.
    "D401",  # Docs strings do not have to be in the imperative mood.

    "ANN101", "ANN102", # Don't require type annotations for 'self' and 'cls'

    "TCH001", "TCH002", "TCH003",  # Don't use if TYPE_CHECKING: blocks.

    "EM101",  # Exceptions can use string literals
]
