# SPDX-FileCopyrightText: 2021 - 2024 Mewbot Developers <mewbot@quicksilver.london>
#
# SPDX-License-Identifier: BSD-2-Clause

name: Publish to Test PyPI

on:
  - push

concurrency:
  group: publish-${{ github.ref }}
  cancel-in-progress: false

env:
  DEFAULT_PYTHON: "3.11"

jobs:
  publish:
    name: Publish Packages
    runs-on: ubuntu-latest

    if: always()

    permissions:
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python ${{ env.DEFAULT_PYTHON }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
          cache: pip
          cache-dependency-path: pyproject.toml

      - name: Install dependencies
        run: pip install build --user

      - name: Build a binary wheel and a source tarball
        run: |
          printf "%s\n" "0.dev${{ github.run_id }}" >version
          python -m build --sdist --wheel --outdir dist/

      - name: Archive installation artifacts
        uses: actions/upload-artifact@v4
        with:
          name: builds
          path: dist

      - name: Publish distribution packages to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
